icons_format = "{icon}"

[theme]
theme = "semi-native"
[theme.overrides]
idle_bg = "#000000"
#idle_fg = "#dfdfdf"
separator = ""

[icons]
icons = "material-nf"
#[icons.overrides]
#bat = ["|E|", "|_|", "|=|", "|F|"]
#bat_charging = "|^| "

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(w:25, rot_interval:0.4, rot_separator:'   ') |"
short = " $title.str(w:25) |"
[block.theme_overrides]
idle_bg = "#000000"
idle_fg = "#00AFFF"

[[block]]
block = "music"
format = " $icon  * $prev $play $next | - "
interface_name_exclude = [".*kdeconnect.*"]
[[block.click]]
button = "left"
action = "play_pause"
[block.theme_overrides]
info_fg = "#00AFFF"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization.eng(w:4) "
format_alt = " $icon $frequency{ $boost|} "

#[[block]]
#block = "disk_space"
#path = "/"
#alert_unit = "GB"
#info_type = "available"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon /+Ex:[$available.eng(hide_unit:true)"
#format_alt = " $icon /+Ex:[$available.eng(hide_unit:true)/$total.eng(hide_unit:true)"
#
#
#[[block]]
#block = "disk_space"
#path = "/run/media/noncomplete/the_hoard/"
#alert_unit = "GB"
#info_type = "available"
#alert = 5.0
#warning = 10.0
#format = "+$available.eng(hide_unit:true)]"
#format_alt = "+$available.eng(hide_unit:true)/$total.eng(hide_unit:true)]"
#
[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

#[[block]]
#block = "backlight"
#device = "intel_backlight"

#[[block]]
#block = "hueshift"
#step = 50
#click_temp = 3500
#format = " 󱎴 $temperature "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $icon {$signal_strength|Wired connection} ( $speed_down.eng(prefix:K, w:4))"
[[block.click]]
button = "left"
cmd = "exec gnome-terminal -- nmtui"

[[block]]
block = "temperature"
format = " $icon $max"
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

#[[block]]
#block = "uptime"
#interval = 3600  # update every hour

# Prayer notification
[[block]]
block = "custom"
command = "echo 󰖔 "
interval = "once"
[[block.click]]
button = "left"
cmd = "~/Documents/rust/prayer_notifier/target/release/prayer_notifier"

[[block]]
block = "taskwarrior"
interval = 60
format = " 󰄹  $count.eng(w:1) tasks "
format_singular = " 󰄹  1 task "
format_everything_done = " 󰄸  "
warning_threshold = 8
critical_threshold = 15
[block.theme_overrides]
warning_fg = "#00A0FF"
[[block.click]]
button = "left"
cmd = "gnome-terminal --geometry=60x20 -- watch -n 60 task"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m/%y %R') "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1))|(0)}"
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "battery"
format = " $icon $percentage $time "
full_format = "   "
[block.theme_overrides]
idle_fg = "#00AFFF"
