icons_format = "{icon}"
error_format = "  "

[theme]
theme = "semi-native"
[theme.overrides]
idle_bg = "#000000"
#idle_fg = "#dfdfdf"
separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(w:40, rot_interval:0.4, rot_separator:'   ') |"
short = " $title.str(w:40) |"
[block.theme_overrides]
idle_bg = "#000000"
idle_fg = "#00AFFF"


[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization.eng(w:4) "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available+"
format_alt = "$icon $percentage A+"

[[block]]
block = "disk_space"
path = "/mnt/bbb69f90-d83b-444e-a9d6-7db272b6793f/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$available"
format_alt = "$percentage A"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "hueshift"
step = 50
click_temp = 3500
format = " 󱎴  $temperature "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid.str(w:5)..|Wired connection} [$device] ( $speed_down.eng(prefix:K, w:4))"
[[block.click]]
button = "left"
cmd = "exec gnome-terminal -- impala"

[[block]]
block = "temperature"
format = " $icon $max"
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

#[[block]]
#block = "custom"
#command = "~/scripts/idle_state_view.sh"
#json = true
#interval = 1
#[[block.click]]
#button = "left"
#cmd = "~/scripts/idle_state_toggle.sh"
#[block.theme_overrides]
#good_fg = "#00AFFF"


[[block]]
block = "music"
format = " $icon  $prev $play $next | - "
interface_name_exclude = [".*kdeconnect.*"]
[[block.click]]
button = "left"
action = "play_pause"
[block.theme_overrides]
info_fg = "#00AFFF"

[[block]]
block = "time"
interval = 10
format = " $icon $timestamp.datetime(f:'%a%Y%m%d')"

[[block]]
block = "time"
interval = 10 
format = "$timestamp.datetime(f:'%R') "
[block.theme_overrides]
idle_fg = "#00afff"

#[[block]]
#block = "custom"
#command = "~/scripts/show_hidden_wins.sh"
#interval = 1

#[[block]]
#block = "pomodoro"
#notify_cmd = "notify-send '{msg}'"
#blocking_cmd = false
#format = " $icon { $message | }"

[[block]]
block = "tea_timer"
format = " $icon {$minutes:$seconds |}"
done_cmd = "notify-send 'Timer Finished'"

[[block]]
block = "custom"
command = "echo  "
interval = "once"
[[block.click]]
button = "left"
cmd = "~/scripts/idle_state_toggle.sh"
#[block.theme_overrides]
#good_fg = "#00AFFF"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1))|(0)}"
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "weather"
format = " $icon $temp"
autolocate = false
[block.service]
name = "metno"
coordinates = ["24.851","89.3711"]

[[block]]
block = "battery"
format = " $icon $percentage $time "
full_format = "   "
[block.theme_overrides]
idle_fg = "#00AFFF"
