initial_screen = "queue"
use_nerdfont = true
volnorm = false
notify = true
bitrate = 320
statusbar_format = "%title - %artists - %album"

[track_format]
left = "%title"
center = "%artists - %album"
right = "%saved %duration"

[notification_format]
title = "%title"
body = "%artists - %album"

[theme]
background = "#000000"
primary = "#C3F6FF"
secondary = "#A9FFFC"
title = "#00FFFF"
playing = "#00FFFF"
playing_selected = "#00AAFF"
playing_bg = "#004444"
highlight = "#AADDFF"
highlight_bg = "#000055"
error = "#FFE4E4"
error_bg = "#7E0000"
statusbar = "#7FBFFF"
statusbar_progress = "#009C9C"
statusbar_progress_bg = "#000000"
statusbar_bg = "#000000"
cmdline = "#BFE1FF"
cmdline_bg = "#000000"

